package clases;
// Generated 14/09/2017 20:46:18 by Hibernate Tools 4.3.1



/**
 * Celulares generated by hbm2java
 */
public class Celulares  implements java.io.Serializable {


     private Integer id;
     private String marca;
     private String modelo;
     private Integer precio;

    public Celulares() {
    }

    public Celulares(String marca, String modelo, Integer precio) {
       this.marca = marca;
       this.modelo = modelo;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


